name: deplot react


on:
    push:
        branches:
            - master



jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - uses: action/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t  adawy1/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true adawy1/react-test npm run test